=== SethFalco/commandler/core/src/main/resources/commandler.xsd
<?xml version="1.1" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://commandler.elypia.com"
           xmlns="https://commandler.elypia.com"
           elementFormDefault="qualified"
           xml:lang="EN">

  <xs:annotation>
    <xs:documentation>
      Commandler 4.0.0 - August 24th 2019
      This is the XML Schema for the Commandler configuration file.
      The file should be named "commandler.xml" in the classpath.
    </xs:documentation>
  </xs:annotation>

  <xs:element name="configuration">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="commandler">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="controller" type="controller" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element name="adapter" type="adapter" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element name="messenger" type="messenger" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <xs:simpleType name="pojo">
    <xs:restriction base="xs:string">
      <xs:pattern value="(?i)[A-Z\d.]+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="method">
    <xs:restriction base="xs:string">
      <xs:pattern value="(?i)[A-Z\d]+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="array">
    <xs:list itemType="xs:string"/>
  </xs:simpleType>

  <xs:complexType name="property">
    <xs:attribute name="key" type="pojo"/>
    <xs:attribute name="value" type="array" use="required"/>
  </xs:complexType>

  <xs:complexType name="element">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="description" type="xs:string" minOccurs="0"/>
      <xs:element name="property" type="property" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="controller">
    <xs:complexContent>
      <xs:extension base="element">
        <xs:all>
          <xs:element name="group" type="xs:string" default="Miscellaneous" minOccurs="0"/>
          <xs:element name="hidden" type="xs:boolean" default="false" minOccurs="0"/>
          <xs:element name="command" type="command" minOccurs="0"/>
        </xs:all>
        <xs:attribute name="type" type="xs:string" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="command">
    <xs:complexContent>
      <xs:extension base="element">
        <xs:sequence>
          <xs:element name="hidden" type="xs:boolean" default="false" minOccurs="0"/>
          <xs:element name="static" type="xs:boolean" default="false" minOccurs="0"/>
          <xs:element name="default" type="xs:boolean" default="false" minOccurs="0"/>
          <xs:element name="param" type="param" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="method" type="method" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="param">
    <xs:complexContent>
      <xs:extension base="element">
        <xs:sequence>
          <xs:element name="defaultValue" type="xs:string" minOccurs="0"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="compatible">
    <xs:sequence>
      <xs:element name="type" type="pojo" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="adapter">
    <xs:sequence>
      <xs:element name="compatible" type="compatible" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="type" type="pojo" use="required"/>
  </xs:complexType>

  <xs:complexType name="messenger">
    <xs:sequence>
      <xs:element name="provides" type="pojo"/>
      <xs:element name="compatible" type="compatible" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="type" type="pojo" use="required"/>
  </xs:complexType>
</xs:schema>

=== SethFalco/commandler/core/src/main/resources/commandler.xml
<?xml version="1.1" encoding="UTF-8"?>
<configuration xmlns="https://commandler.elypia.com"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://commandler.elypia.com commandler.xsd">
  <commandler>
    <controller type="com.elypia.commandler.DefaultHelpController">
      <name>Help</name>
      <group>Guidance</group>
      <description>Offer generic help through all the modules in this bot.</description>
      <property key="com.elypia.commandler.dispatchers.StandardDispatcher.aliases" value="help, h"/>
      <command method="getGroups">
        <name>Show Groups</name>
        <description>Display a list of all metaCommand categories.</description>
        <default>true</default>
        <property key="com.elypia.commandler.dispatchers.StandardDispatcher.aliases" value="groups, group"/>
      </command>
      <command method="getModules">
        <name>Show Modules</name>
        <description>Display a list of all modules in a category.</description>
        <property key="com.elypia.commandler.dispatchers.StandardDispatcher.aliases" value="modules, module"/>
        <param>
          <name>group</name>
          <description>The group to list modules for.</description>
        </param>
      </command>
      <command method="getCommands">
        <name>Show Commands</name>
        <description>Display a list of all metaCommands in a module.</description>
        <property key="com.elypia.commandler.dispatchers.StandardDispatcher.aliases" value="commands, command"/>
        <param>
          <name>modules</name>
          <description>The module to list commands for.</description>
        </param>
      </command>
    </controller>
    <adapter type="com.elypia.commandler.adapters.BooleanAdapter">
      <compatible>
        <type>java.lang.Boolean</type>
        <type>boolean</type>
      </compatible>
    </adapter>
    <adapter type="com.elypia.commandler.adapters.CharAdapter">
      <compatible>
        <type>java.lang.Character</type>
        <type>char</type>
      </compatible>
    </adapter>
    <adapter type="com.elypia.commandler.adapters.DurationAdapter">
      <compatible>
        <type>java.time.Duration</type>
      </compatible>
    </adapter>
    <adapter type="com.elypia.commandler.adapters.EnumAdapter">
      <compatible>
        <type>java.lang.Enum</type>
      </compatible>
    </adapter>
    <adapter type="com.elypia.commandler.adapters.LocaleAdapter">
      <compatible>
        <type>java.util.Locale</type>
      </compatible>
    </adapter>
    <adapter type="com.elypia.commandler.adapters.NumberAdapter">
      <compatible>
        <type>java.lang.Number</type>
        <type>double</type>
        <type>float</type>
        <type>long</type>
        <type>int</type>
        <type>short</type>
        <type>byte</type>
      </compatible>
    </adapter>
    <adapter type="com.elypia.commandler.adapters.StringAdapter">
      <compatible>
        <type>java.lang.CharSequence</type>
      </compatible>
    </adapter>
    <adapter type="com.elypia.commandler.adapters.TimeUnitAdapter">
      <compatible>
        <type>java.util.concurrent.TimeUnit</type>
      </compatible>
    </adapter>
    <adapter type="com.elypia.commandler.adapters.UrlAdapter">
      <compatible>
        <type>java.net.URL</type>
      </compatible>
    </adapter>
  </commandler>
</configuration>

=== SethFalco/commandler/console/src/main/resources/commandler-console.xml
<?xml version="1.1" encoding="UTF-8"?>
<commandler xmlns="https://commandler.elypia.com"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="https://commandler.elypia.com commandler.xsd">
  <messengers>
    <messenger>
      <type>com.elypia.commandler.console.messengers.MiscMessenger</type>
      <provides>java.lang.String</provides>
      <compatible>
        <type>java.lang.Boolean</type>
        <type>java.lang.CharSequence</type>
        <type>java.lang.Character</type>
        <type>java.net.URL</type>
        <type>boolean</type>
        <type>char</type>
      </compatible>
    </messenger>
    <messenger>
      <type>com.elypia.commandler.console.messengers.NumberMessenger</type>
      <provides>java.lang.Number</provides>
      <compatible>
        <type>java.lang.Number</type>
        <type>double</type>
        <type>float</type>
        <type>long</type>
        <type>int</type>
        <type>short</type>
        <type>byte</type>
      </compatible>
    </messenger>
  </messengers>
</commandler>
